import img1 from "../assets/images/nature.jpg";

const servicesCardData = [
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Six Sigma",
    value: "ISO 9001:2015 REFRESHER COURSEISO",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "WHY ", highlight: false },
      { text: "ISO 9001:2015", highlight: true },
      { text: " REFRESHER COURSE?", highlight: false },
    ],
    paragrapgh: [
      "The ISO 9001:2015 Refresher Course is designed forprofessionals who already have a working knowledge of Quality Management Systems and want to realign withcurrent ISO 9001 requirements. The training revisits coreconcepts, clarifies key clauses, and highlights practicalimplications of the standard to ensure effectiveimplementation and sustained compliance. It helpsparticipants sharpen their understanding and confidentlysupport QMS maintenance and continual improvement.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Review updates and critical interpretations of ISO 9001:2015",
      "Apply ISO 9001 requirements to real-world operational scenarios",
      "Gain practical insights into continual improvement and performance evaluation ",
      "Discuss case studies showcasing effective and successful QMS implementation",
    ],
    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Overview and intent of ISO 9001:2015 clauses ",
      "Key updates, interpretations, and common gaps in implementation",
      "Quality Management Principles and their practical application ",
      "Process approach, risk-based thinking, and PDCA cycle ",
      "Documentation and record control: what to retain, what to simplify ",
      "Roles, responsibilities, and leadership involvement in QMS",
      "Case Discussions and Interactive Q&A ",
    ],
    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Six Sigma",
    value: "ISO 9001:2015 AWARENESS SESSION",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "WHY ", highlight: false },
      { text: "ISO 9001:2015", highlight: true },
      { text: " AWARENESS SESSION?", highlight: false },
    ],
    paragrapgh: [
      "The ISO 9001:2015 Awareness Session is designed to build a common understanding of QMS requirements across all levels of the organization. It helps employees recognize how ISO 9001 applies to their daily roles, why compliance matters, and how individual actions contribute to quality objectives and customer satisfaction. This session supports smooth QMS implementation and strengthens engagement during audits and continual improvement initiatives.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Clear understanding of ISO 9001:2015 intent and key requirements",
      "Awareness of employee roles and responsibilities within the QMS",
      "Improved alignment between day-to-day activities and quality objectives",
      "Better preparedness for internal and external audits",
      "Enhanced ownership and participation in quality improvement ",
    ],
    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Purpose and benefits of ISO 9001:2015 ",
      "Overview of the standard and High-Level Structure (Annex SL) ",
      "Quality policy, objectives, and their relevance to employees ",
      "Process approach and riskbased thinking in daily work",
      "Roles of employees in maintaining QMS effectiveness",
      "Audit awareness and do’s & don’ts during assessments",
      "Case Discussions and Interactive Q&A ",
    ],
    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Six Sigma",
    value: "FIRE SAFETY TRAINING",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "WHY ", highlight: false },
      { text: "FIRE SAFETY?", highlight: true },
    ],
    paragrapgh: [
      "Fire incidents escalate rapidly and cause severe loss to life, assets, and business continuity, most fires result from preventable unsafe conditions and delayed response. Fire Safety Training focuses on building awareness, preparedness, and correct response behaviors so employees can prevent fires, react quickly, and minimize impact. Ratherthan only relying on equipment and procedures, this training empowers people to recognize fire risks, use firefighting systems correctly, and respond calmly during emergencies.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Reduced fire risk through early hazard identification and prevention ",
      "Faster, safer response during fire and evacuation scenarios ",
      "Improved confidence in using fire extinguishers and emergency systems ",
      "Compliance with statutory and insurance requirements ",
      "A prepared workforce aligned with emergency response roles and responsibilities ",
    ],
    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Introduction to Fire Behavior and the Fire Triangle ",
      "Types and Classes of Fire",
      "Common Workplace Fire Hazards and Prevention Tips ",
      "Introduction to Fire Extinguishers and Their Applications ",
      "Emergency Evacuation Procedures and Safe Assembly ",
      "Roles of Employees During a Fire Emergency ",
      "Basic Fire Safety Do’s & Don’ts ",
      "Case Discussions and Interactive Q&A ",
    ],
    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Six Sigma",
    value: "BEHAVIOR BASED SAFETY (BBS) TRAINING",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "WHY ", highlight: false },
      { text: "BBS SAFETY?", highlight: true },
    ],
    paragrapgh: [
      "It is found that 90% of workplace accidents are triggered by ‘unsafe acts’. Behavioural safety provides a way of reducing injuries, through the analysis of the risk behaviors in the current work environment. BBS's purpose is not to enforce safety rules, force change, etc. Its purpose is to identify safe and at-risk behaviours, identify the possibility for injury, communicating the risk & helping to identify safer solutions.",
      "Despite having introduced numerous safety systems, which have reduced hazards & improved safety performance,accidents could not get eliminated. Rather stressing on implementation of procedures / rules & regulations, wemotivate people for behaving safely",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Reduced incidents and injuries through proactive behavior change ",
      "Improved employee engagement in safety programs ",
      "A sustainable, observation-driven safety culture ",
      "Tools for real-time feedback and continuous improvement",
      "Aligned leadership and workforce on safety expectations ",
    ],
    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Introduction to Fire Behavior and the Fire Triangle ",
      "Types and Classes of Fire",
      "Common Workplace Fire Hazards and Prevention Tips ",
      "Introduction to Fire Extinguishers and Their Applications ",
      "Emergency Evacuation Procedures and Safe Assembly ",
      "Roles of Employees During a Fire Emergency ",
      "Basic Fire Safety Do’s & Don’ts ",
      "Case Discussions and Interactive Q&A ",
    ],
    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Six Sigma",
    value: "ISO 9001:2015 INTRODUCTION TO QMS",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "WHY INTRODUCTION TO", highlight: false },
      { text: " QMS? ", highlight: true },
    ],
    paragrapgh: [
      "The ISO 9001:2015 Introduction to QMS training provides a clear and practical overview of Quality Management System fundamentals for professionals and organizations beginning their ISO journey. The course explains the intent, structure, and key requirements of ISO 9001, helping participants understand how a process-based approach improves quality, efficiency, and customer satisfaction. It sets a strong foundation for effective implementation and future certification.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Understand the basic principles and structure of ISO 9001:2015",
      "Identify key ISO 9001 requirements and their role in continual improvement ",
      "Learn essential documentation and record-keeping practices for compliance ",
      " Gain clarity on the steps to initiate ISO 9001 certification for an organization",
    ],
    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Overview of Quality Management Systems and ISO philosophy ",
      "ISO 9001:2015 structure (High-Level Structure – Annex SL) ",
      "Quality management principles and process approach ",
      "Documented information: policies, procedures, and records ",
      "Basic roadmap for ISO 9001 implementation and certification",
      "Case Discussions and Interactive Q&A ",
    ],
    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "ISO 9001:2015 Internal Auditors Training Course",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "ISO ", highlight: false },
      { text: "9001:2015 ", highlight: true },
      { text: "Internal Auditors Training Course", highlight: false },
    ],
    paragrapgh: [
      "The ISO 9001:2015 Internal Auditors Training Course is designed to develop competent internal auditors who can effectively evaluate, maintain, and improve an organization’s Quality Management System (QMS).",
      "Internal audits are a critical requirement of ISO 9001:2015 and play a key role in ensuring compliance, effectiveness, and continual improvement. This training helps participants understand not just how to audit, but why auditing is essential for identifying risks, nonconformities, and improvement opportunities. The course emphasizes a process-based and risk-based auditing approach, aligned with ISO 19011 guidelines.",
      "It equips participants with the confidence and skills to conduct value-added internal audits, rather than checklist-based or compliance-only audits.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Understand ISO 9001:2015 requirements from an internal auditor’s viewpoint",
      "Plan, conduct, and report effective internal audits",
      "Apply process approach, PDCA, and risk-based thinking during audits",
      "Identify nonconformities, risks, and improvement opportunities",
      "Communicate audit findings confidently and professionally",
      "Support continual improvement and management review inputs",
      "Add value to the organization beyond basic compliance",
    ],
    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Overview and intent of ISO 9001:2015 clauses from an auditor’s perspective",
      "Internal audit requirements as per ISO 9001:2015",
      "Audit principles and guidelines based on ISO 19011",
      "Audit planning and preparation",
      "Process-based and risk-based audit approach",
      "Developing audit checklists and audit trails",
      "Conducting opening and closing meetings",
      "Interview techniques and evidence collection",
      "Identifying, writing, and grading nonconformities",
      "Root cause understanding and corrective action follow-up",
      "Audit reporting and monitoring audit effectiveness",
      "Case studies, role plays, and mock audits",
    ],
    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "ISO 9001:2015 Certified Lead Implementor Program",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "ISO ", highlight: false },
      { text: "9001:2015 ", highlight: true },
      { text: "Certified Lead Implementor Program", highlight: false },
    ],
    paragrapgh: [
      "The ISO 9001:2015 Certified Lead Implementor Program is designed for professionals who are responsible for designing, implementing, managing, and improving a Quality Management System (QMS) in line with ISO 9001:2015.",
      "This program goes beyond awareness or auditing and focuses on end-to-end QMS implementation. It equips participants with the knowledge and practical skills needed to translate ISO 9001 requirements into effective business processes, align quality objectives with organizational strategy, and ensure sustained compliance and continual improvement.",
      "The training is ideal for those who want to lead QMS implementation projects, support certification readiness, and act as a key link between top management, process owners, and external auditors.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Lead the design and implementation of an ISO 9001:2015 compliant QMS",
      "Interpret and apply ISO 9001 requirements to real business processes",
      "Identify risks, opportunities, and improvement areas across the organization",
      "Develop and maintain effective QMS documentation",
      "Coordinate internal audits and management reviews",
      "Support successful ISO 9001 certification and ongoing compliance",
      "Drive continual improvement and customer satisfaction",
      "Act confidently as a Lead Implementor or QMS Representative",
    ],
    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Detailed interpretation of ISO 9001:2015 clauses and their intent",
      "Understanding organizational context, interested parties, and scope",
      "Leadership roles, responsibilities, and strategic alignment of QMS",
      "Establishing and managing process-based QMS",
      "Risk-based thinking and opportunity management",
      "Setting quality objectives, KPIs, and performance monitoring",
      "Documentation strategy – manuals, procedures, records, and simplification",
      "Resource management, competence, and awareness",
      "Operational planning and control",
      "Monitoring, measurement, analysis, and evaluation",
      "Internal audit, management review, and continual improvement",
      "Preparing for certification and surveillance audits",
      "Implementation case studies, workshops, and practical exercises",
      "Interactive discussions and Q&A sessions",
    ],
    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "ISO 9001:2015 Lead Auditors Training Course",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "ISO ", highlight: false },
      { text: "9001:2015 ", highlight: true },
      { text: "Lead Auditors Training Course", highlight: false },
    ],
    paragrapgh: [
      "The ISO 9001:2015 Lead Auditor Training Course is designed for professionals who want to develop the competence to plan, conduct, lead, and manage first-, second-, and third-party audits of a Quality Management System (QMS) in accordance with ISO 9001:2015.",
      "This course builds advanced auditing skills by combining in-depth standard interpretation, audit leadership techniques, and practical audit simulations. It follows the principles and guidelines of ISO 19011 and prepares participants to confidently lead audit teams, communicate with top management, and ensure objective, value-added audit outcomes.",
      "The training is ideal for those aspiring to become certification body auditors, lead internal auditors, supplier auditors, or QMS consultants.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Interpret ISO 9001:2015 requirements with auditor-level depth",
      "Plan and lead effective and compliant QMS audits",
      "Manage audit teams and communicate professionally with stakeholders",
      "Identify systemic issues, risks, and improvement opportunities",
      "Write high-quality audit reports aligned with certification body expectations",
      "Support organizations in achieving and maintaining ISO 9001 certification",
      "Build competence toward becoming a Certified ISO 9001 Lead Auditor",
    ],
    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Detailed interpretation of ISO 9001:2015 clauses from a lead auditor’s perspective",
      "Audit principles, ethics, and competence requirements (ISO 19011)",
      "Roles and responsibilities of a Lead Auditor",
      "Audit types: first-party, second-party, and third-party audits",
      "Audit planning, audit programs, and team management",
      "Process-based and risk-based audit approach",
      "Developing audit checklists and audit trails",
      "Conducting opening meetings, interviews, and evidence collection",
      "Identifying, classifying, and reporting nonconformities",
      "Writing clear, objective, and actionable audit findings and reports",
      "Handling difficult audit situations and auditee interactions",
      "Audit follow-up, corrective actions, and verification of effectiveness",
      "Mock audits, role plays, and case studies",
      "Interactive discussions and Q&A sessions",
    ],
    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "ISO 9001:2015 Quality Management Principles",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "ISO ", highlight: false },
      { text: "9001:2015 ", highlight: true },
      { text: "Quality Management Principles", highlight: false },
    ],
    paragrapgh: [
      "The ISO 9001:2015 Quality Management Principles (QMPs) form the foundation of an effective Quality Management System. Understanding these principles helps organizations move beyond clause-by-clause compliance and build a culture focused on customer satisfaction, leadership, and continual improvement.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Clearly understand and explain the seven Quality Management Principles",
      "Apply QMPs to design, implement, and improve QMS processes",
      "Strengthen leadership involvement and employee engagement",
      "Improve customer satisfaction and process performance",
      "Make informed, evidence-based decisions",
      "Build strong and effective supplier and stakeholder relationships",
      "Support continual improvement beyond audit-driven compliance",
    ],
    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Customer Focus – meeting and exceeding customer expectations",
      "Leadership – establishing unity of purpose and direction",
      "Engagement of People – competence, empowerment, and accountability",
      "Process Approach – managing activities as interrelated processes",
      "Improvement – continual improvement as a permanent objective",
      "Evidence-Based Decision Making – using data and information effectively",
      "Relationship Management – managing suppliers and interested parties",
    ],
    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "ISO 9001:2015 Customer Focus and Satisfaction",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "ISO ", highlight: false },
      { text: "9001:2015 ", highlight: true },
      { text: "Customer Focus and Satisfaction", highlight: false },
    ],
    paragrapgh: [
      "Customer focus is the first and most important Quality Management Principle of ISO 9001:2015. This training is designed to help organizations understand how to consistently identify customer needs, meet requirements, and enhance customer satisfaction in a structured and measurable way.",
      "Many organizations collect customer feedback but fail to effectively analyze or act on it. This program explains how ISO 9001:2015 integrates customer focus into planning, operations, performance evaluation, and improvement, ensuring customer satisfaction is not incidental but systematically managed.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Understand and apply customer focus requirements of ISO 9001:2015",
      "Identify and manage customer requirements effectively",
      "Establish effective methods to measure and monitor customer satisfaction",
      "Analyze customer feedback to identify risks and improvement opportunities",
      "Improve customer communication and complaint handling",
      "Enhance customer trust, loyalty, and retention",
    ],
    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Understanding customer requirements (stated, implied, and statutory)",
      "Customer focus requirements in ISO 9001:2015 clauses",
      "Identifying interested parties and their expectations",
      "Aligning products and services with customer needs",
      "Managing customer communication and feedback",
      "Methods for measuring customer satisfaction",
      "Analysis and evaluation of customer feedback data",
      "Handling customer complaints and nonconformities",
      "Linking customer feedback to risk-based thinking",
      "Using customer satisfaction data for continual improvement",
      "Case studies and real-life examples",
      "Interactive discussions and Q&A sessions",
    ],
    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "ISO 9001:2015 Integrated with Other Management System",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "ISO ", highlight: false },
      { text: "9001:2015 ", highlight: true },
      { text: "Integrated with Other Management System", highlight: false },
    ],
    paragrapgh: [
      "Organizations today often operate multiple management systems such as ISO 14001 (Environmental), ISO 45001 (OH&S), ISO 27001 (Information Security), and ISO 22000 (Food Safety). Managing these systems separately can lead to duplication, inefficiencies, and increased costs.",
      "The ISO 9001:2015 Integrated Management Systems (IMS) approach enables organizations to align, combine, and streamline common requirements across different ISO standards using the Annex SL high-level structure. This training helps participants understand how to build and maintain an integrated system that improves efficiency, consistency, and overall organizational performance.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Understand how ISO 9001:2015 aligns with other ISO management systems",
      "Design and implement an Integrated Management System (IMS)",
      "Reduce duplication of documents, audits, and processes",
      "Improve coordination across quality, environment, safety, and other functions",
      "Conduct integrated audits and management reviews",
      "Enhance organizational efficiency and compliance",
      "Support continual improvement across multiple management systems",
    ],

    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Understanding Annex SL / High-Level Structure (HLS)",
      "Common clauses across ISO management system standards",
      "Integration of context of the organization and interested parties",
      "Unified approach to leadership, policy, and objectives",
      "Integrated risk and opportunity management",
      "Common documented information control",
      "Integrated operational planning and controls",
      "Combined competence, awareness, and communication",
      "Integrated internal audits and management reviews",
      "Performance evaluation and continual improvement across systems",
      "Benefits and challenges of integration",
      "Practical examples and case studies",
      "Interactive discussions and Q&A session",
    ],

    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "ISO 9001:2015 vs IATF 16949:2016",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "ISO ", highlight: false },
      { text: "9001:2015 ", highlight: true },
      { text: "vs IATF 16949:2016", highlight: false },
    ],
    paragrapgh: [
      "ISO 9001:2015 is a generic Quality Management System standard applicable to all industries, IATF 16949:2016 is a sector-specific QMS standard for the automotive industry. Many organizations struggle to understand the additional requirements, expectations, and gaps between these two standards.",
      "This training is designed to clearly explain the similarities, differences, and added automotive-specific requirements of IATF 16949:2016 in comparison with ISO 9001:2015. It helps organizations transitioning from ISO 9001 to IATF 16949 or managing both standards to implement requirements effectively and avoid audit nonconformities.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Clearly understand the key differences and similarities between ISO 9001 and IATF 16949",
      "Identify additional requirements needed for automotive compliance",
      "Assess gaps when transitioning from ISO 9001 to IATF 16949",
      "Implement customer-specific and automotive requirements effectively",
      "Prepare confidently for IATF certification and surveillance audits",
      "Reduce audit risks and nonconformities",
      "Support continual improvement in automotive QMS",
    ],

    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Overview and purpose of ISO 9001 vs IATF 16949",
      "Common structure based on Annex SL",
      "Clauses of ISO 9001 adopted by IATF 16949",
      "Additional IATF 16949 requirements beyond ISO 9001",
      "Automotive-specific requirements and expectations",
      "Customer-specific requirements (CSRs)",
      "Risk-based thinking vs product and process risk management",
      "Documentation and record control differences",
      "Change management and product safety requirements",
      "Internal audit, second-party, and layered process audits",
      "Management review and performance evaluation differences",
      "Common transition challenges and implementation gaps",
      "Case studies and practical examples",
      "Interactive discussions and Q&A sessions",
    ],

    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "IATF 16949:2016 Awareness Session",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "IATF ", highlight: false },
      { text: "16949:2016 ", highlight: true },
      { text: "Awareness Session", highlight: false },
    ],
    paragrapgh: [
      "The IATF 16949:2016 Awareness Session provides a basic understanding of the automotive Quality Management System requirements for organizations involved in automotive manufacturing and supply chains.",
      "This session explains what IATF 16949 is, why it is important, and how it helps improve product quality, reduce defects, and meet customer-specific requirements. It creates awareness of key QMS concepts and prepares participants for further implementation or internal auditor training.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Basic understanding of IATF 16949:2016 requirements",
      "Awareness of automotive quality system expectations",
      "Understanding of roles and responsibilities within IATF QMS",
      "Knowledge of how IATF helps improve quality and reduce defects",
      "Readiness for implementation, internal audits, or advanced training",
    ],

    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Introduction to IATF 16949:2016 and automotive QMS",
      "Difference between ISO 9001 and IATF 16949",
      "Structure and key requirements of IATF 16949:2016",
      "Customer-specific requirements (CSR) – basic understanding",
      "Risk-based thinking and process approach in automotive QMS",
      "Importance of documented information",
      "Role of employees in meeting IATF requirements",
      "Overview of internal audits and continual improvement",
    ],

    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "IATF 16949:2016 Internal Auditors Training Course",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "IATF ", highlight: false },
      { text: "16949:2016 ", highlight: true },
      { text: "Internal Auditors Training Course", highlight: false },
    ],
    paragrapgh: [
      "The IATF 16949:2016 Internal Auditors Training Course is designed to develop competent internal auditors who can plan, conduct, and report internal audits for an automotive Quality Management System.",
      "Internal audits are a key requirement of IATF 16949 and help organizations ensure process control, product quality, and customer satisfaction. This course explains how to audit automotive processes, understand customer-specific requirements (CSR), and identify risks, nonconformities, and improvement opportunities.",
      "The training focuses on a process-based, risk-based, and automotive-specific audit approach, aligned with ISO 19011, enabling participants to perform value-added internal audits rather than checklist-only audits.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Clear understanding of IATF 16949:2016 requirements from an internal auditor’s view",
      "Ability to plan, conduct, and report effective automotive internal audits",
      "Practical application of process approach, risk-based thinking, and PDCA",
      "Skills to identify nonconformities, risks, and improvement opportunities",
      "Confidence to communicate audit findings professionally",
      "Capability to support continual improvement and management review",
      "Readiness to support certification and customer audits",
    ],

    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Overview of IATF 16949:2016 requirements from an auditor’s perspective",
      "Relationship between ISO 9001 and IATF 16949",
      "Automotive process approach and risk-based thinking",
      "Internal audit requirements as per IATF 16949:2016",
      "Audit principles and guidelines based on ISO 19011",
      "Audit planning, scope, criteria, and preparation",
      "Auditing core automotive processes (production, quality, support)",
      "Understanding and auditing Customer-Specific Requirements (CSR)",
      "Interview techniques and objective evidence collection",
      "Identifying, documenting, and grading nonconformities",
      "Root cause understanding and corrective action follow-up",
      "Audit reporting and monitoring audit effectiveness",
      "Case studies, mock audits, and interactive discussions",
    ],

    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "Statistical Process Control (SPC)",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "Statistical Process Control ", highlight: false },
      { text: "(SPC) ", highlight: true },
      // { text: "Internal Auditors Training Course", highlight: false },
    ],
    paragrapgh: [
      "The Statistical Process Control (SPC) Training Course helps participants understand how to monitor, control, and improve processes using basic statistical tools.",
      "SPC is widely used in manufacturing and automotive industries to reduce variation, prevent defects, and improve process consistency. This course explains why SPC is important, how to read control charts, and how to take correct actions before problems occur, instead of reacting after defects are produced.",
      "The training focuses on practical application, helping participants use SPC tools effectively on the shop floor and in quality control activities.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Clear understanding of SPC concepts and tools",
      "Ability to monitor and control process performance",
      "Skills to identify process variation and early warning signs",
      "Knowledge to reduce defects and improve process consistency",
      "Confidence to apply SPC in daily quality and production activities",
      "Better support for IATF 16949 and ISO 9001 requirements",
    ],

    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Introduction to SPC concepts and benefits",
      "Process variation: common cause vs special cause",
      "Basic statistics for SPC (mean, range, standard deviation)",
      "Types of control charts (X̄-R, X̄-S, I-MR, P, NP, C, U)",
      "How to plot, read, and interpret control charts",
      "Process capability concepts (Cp, Cpk)",
      "Actions to take when processes go out of control",
      "Link between SPC, quality improvement, and customer requirements",
      "Practical examples, exercises, and discussions",
    ],

    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "Measurement System Analysis (MSA)",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "Measurement System Analysis ", highlight: false },
      { text: "(MSA) ", highlight: true },
      // { text: "Internal Auditors Training Course", highlight: false },
    ],
    paragrapgh: [
      "The Measurement System Analysis (MSA) Training Course helps participants understand how to evaluate and improve measurement systems used in quality control and inspection.",
      "Accurate measurements are critical for correct decisions on product acceptance, process capability, and customer satisfaction. This course explains why measurement errors occur, how to assess measurement systems, and how to ensure that measurement data is reliable and consistent.",
      "The training focuses on practical understanding of MSA tools, commonly required in IATF 16949 and automotive quality systems.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Clear understanding of MSA requirements and concepts",
      "Ability to evaluate measurement system performance",
      "Knowledge to conduct and interpret Gage R&R studies",
      "Improved confidence in measurement data and inspection results",
      "Better support for SPC, IATF 16949, and customer requirements",
      "Reduced risk of wrong decisions due to measurement errors",
    ],

    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Introduction to MSA concepts and importance",
      "Types of measurement errors (bias, repeatability, reproducibility, stability, linearity)",
      "Overview of Gage R&R studies (variable and attribute)",
      "Understanding accuracy, precision, and resolution",
      "Data collection and basic statistical concepts",
      "Acceptance criteria and interpretation of MSA results",
      "Common measurement system problems and improvement actions",
      "Link between MSA, SPC, and process capability",
      "Practical examples and exercises",
    ],

    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "Production Part Approval Process (PPAP)",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "Production Part Approval Process ", highlight: false },
      { text: "(PPAP) ", highlight: true },
      // { text: "Internal Auditors Training Course", highlight: false },
    ],
    paragrapgh: [
      "The Production Part Approval Process (PPAP) Training Course helps participants understand how to demonstrate that production processes can consistently produce parts that meet customer requirements.",
      "PPAP is a key requirement in IATF 16949 and is used by automotive customers to ensure product quality, process stability, and risk reduction before mass production. This course explains why PPAP is required, when it must be submitted, and how to prepare PPAP documents correctly.",
      "The training focuses on practical understanding of PPAP elements, enabling participants to confidently support customer approvals and audits.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Clear understanding of PPAP requirements and customer expectations",
      "Ability to prepare and review PPAP documentation",
      "Knowledge of PPAP submission levels and elements",
      "Confidence to support new product launches and changes",
      "Better readiness for customer audits and approvals",
      "Strong support for IATF 16949 compliance",
    ],

    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Introduction to PPAP purpose and requirements",
      "When PPAP submission is required",
      "PPAP submission levels (Levels 1 to 5)",
      "Detailed overview of PPAP elements (18 elements)",
      "Understanding design records and engineering changes",
      "Process Flow Diagram, PFMEA, and Control Plan",
      "Measurement results, MSA, SPC, and capability studies",
      "Part Submission Warrant (PSW) preparation",
      "Common PPAP issues and mistakes",
      "Practical examples and case discussions",
    ],

    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "Problem Solving and Root Cause Analysis",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "Problem ", highlight: false },
      { text: "Solving and Root ", highlight: true },
      { text: "Cause Analysis", highlight: false },
    ],
    paragrapgh: [
      "The Problem Solving and Root Cause Analysis Training Course helps participants learn how to identify problems correctly, find the real root cause, and implement effective corrective actions.",
      "Effective problem solving is critical for reducing defects, preventing recurrence, and improving process performance. This course explains why problems occur, how to analyze them systematically, and how to move from firefighting to permanent solutions.",
      "The training focuses on structured and practical problem-solving methods, commonly required in IATF 16949, ISO 9001, and customer-specific requirements.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Clear understanding of structured problem-solving methods",
      "Ability to identify true root causes, not just symptoms",
      "Skills to develop effective and permanent corrective actions",
      "Confidence to handle quality issues and customer complaints",
      "Improved process performance and defect prevention",
      "Strong support for ISO 9001 and IATF 16949 requirements",
    ],

    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Introduction to problem-solving concepts and benefits",
      "Difference between symptoms and root causes",
      "Structured problem-solving approaches (PDCA, 8D, A3)",
      "Root cause analysis tools (5 Why, Fishbone/Ishikawa)",
      "Problem definition and data collection techniques",
      "Corrective and preventive actions",
      "Verification of effectiveness and sustainability",
      "Linking problem solving with continual improvement",
      "Practical examples, case studies, and exercises",
    ],

    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "Product Failure Mode & Effect Analysis (PFMEA)",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "Product ", highlight: false },
      { text: "Failure Mode & Effect Analysis ", highlight: true },
      { text: "(PFMEA)", highlight: false },
    ],
    paragrapgh: [
      "The Product Failure Mode & Effects Analysis (PFMEA) Training Course helps participants understand how to identify potential product failures early in the design stage and take actions to reduce risk before problems reach the customer.",
      "PFMEA is an important preventive tool used in IATF 16949 and APQP, helping organizations improve product reliability, safety, and customer satisfaction. This course explains why PFMEA is required, how to identify failure modes, and how to prioritize risks using a structured approach.",
      "The training focuses on practical understanding of PFMEA, enabling teams to prevent failures rather than reacting after defects occur.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Clear understanding of PFMEA methodology and requirements",
      "Ability to identify potential product risks early",
      "Skills to prioritize and reduce high-risk failure modes",
      "Improved product quality, reliability, and safety",
      "Strong support for APQP, PPAP, and IATF 16949 compliance",
      "Shift from reactive problem-solving to preventive thinking",
    ],

    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Introduction to FMEA concepts and purpose",
      "Difference between DFMEA and PFMEA",
      "Understanding product functions and requirements",
      "Identifying potential failure modes and effects",
      "Determining causes of failure",
      "Risk evaluation using Severity, Occurrence, and Detection",
      "Action planning to reduce risk",
      "Understanding AIAG–VDA FMEA basics",
      "Link between PFMEA, design control, and quality planning",
      "Practical examples and case studies",
    ],

    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "Key Performance Indicators (KPI)",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "Key Performance Indicators ", highlight: false },
      { text: "(KPI)", highlight: true },
      // { text: "(PFMEA)", highlight: false },
    ],
    paragrapgh: [
      "The Product Failure Mode & Effects Analysis (PFMEA) Training Course helps participants understand how to identify potential product failures early in the design stage and take actions to reduce risk before problems reach the customer.",
      "PFMEA is an important preventive tool used in IATF 16949 and APQP, helping organizations improve product reliability, safety, and customer satisfaction. This course explains why PFMEA is required, how to identify failure modes, and how to prioritize risks using a structured approach.",
      "The training focuses on practical understanding of PFMEA, enabling teams to prevent failures rather than reacting after defects occur.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Clear understanding of KPIs and their importance",
      "Ability to define meaningful KPIs for processes and departments",
      "Skills to monitor performance and identify improvement opportunities",
      "Better data-based decision-making capability",
      "Strong support for ISO 9001 and IATF 16949 compliance",
      "Improved alignment between daily operations and organizational goals",
    ],

    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Introduction to KPIs and performance measurement",
      "Difference between KPIs and metrics",
      "Selecting effective and measurable KPIs",
      "Linking KPIs to quality objectives and business goals",
      "Process, quality, delivery, cost, and safety KPIs",
      "Setting targets, limits, and trends",
      "Monitoring, analyzing, and reporting KPI data",
      "Using KPIs for management review and improvement actions",
      "Common KPI mistakes and best practices",
      "Practical examples and exercises",
    ],

    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "7 QC Tools",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "7 QC ", highlight: false },
      { text: "Tools", highlight: true },
      // { text: "(PFMEA)", highlight: false },
    ],
    paragrapgh: [
      "The 7 QC Tools Training Course helps participants learn how to identify, analyze, and solve quality problems using basic and practical quality tools.",
      "The 7 QC Tools are widely used in manufacturing and service industries to analyze data, identify root causes, and improve processes. This course explains when and how to use each tool, making problem-solving more structured and data-driven.",
      "The training focuses on practical application, helping teams move from assumptions to fact-based decisions.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Clear understanding of all 7 QC Tools",
      "Ability to apply the right tool for problem analysis",
      "Improved problem-solving and analytical skills",
      "Better use of data for quality improvement",
      "Support for ISO 9001 and IATF 16949 requirements",
      "Increased confidence in daily quality improvement activities",
    ],

    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Introduction to the 7 QC Tools and their purpose",
      "Check Sheet – data collection and recording",
      "Pareto Chart – identifying major problems (80/20 rule)",
      "Cause & Effect (Fishbone) Diagram – root cause analysis",
      "Histogram – understanding data distribution",
      "Control Chart – monitoring process stability",
      "Scatter Diagram – identifying relationships between variables",
      "Flow Chart – understanding process flow",
      "Selecting the right tool for the right problem",
      "Practical examples and case studies",
    ],

    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "New 7 QC Tools",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "New ", highlight: false },
      { text: "7 QC ", highlight: true },
      { text: "Tools", highlight: false },
    ],
    paragrapgh: [
      "The New 7 QC Tools Training Course helps participants learn how to analyze complex problems, plan improvements, and make better decisions using management and planning tools.",
      "Unlike the basic 7 QC Tools, the New 7 QC Tools focus more on idea organization, problem structuring, and decision-making, especially when data is limited. These tools are widely used in quality improvement, project management, and root cause analysis.",
      "The training emphasizes practical understanding and real-life application, supporting continual improvement initiatives.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Clear understanding of the New 7 QC Tools",
      "Ability to structure complex problems clearly",
      "Improved planning and decision-making skills",
      "Better teamwork and idea organization",
      "Strong support for quality improvement and problem-solving activities",
      "Enhanced capability to manage risks and improvement projects",
    ],

    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Introduction to New 7 QC Tools and their purpose",
      "Affinity Diagram – organizing ideas and opinions",
      "Relations Diagram – identifying cause-and-effect relationships",
      "Tree Diagram – breaking down problems and solutions",
      "Matrix Diagram – analyzing relationships between factors",
      "Matrix Data Analysis – prioritizing and decision-making",
      "Arrow Diagram – project planning and scheduling",
      "Process Decision Program Chart (PDPC) – risk identification and prevention",
      "Selecting the right tool for planning and improvement",
      "Practical examples and case discussions",
    ],

    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "APQP & PPAP",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "APQP ", highlight: false },
      { text: "& ", highlight: true },
      { text: "PPAP", highlight: false },
    ],
    paragrapgh: [
      "The APQP & PPAP Training Course helps participants understand how to plan product quality in advance and obtain customer approval for production parts.",
      "Advanced Product Quality Planning (APQP) ensures that product and process risks are identified early, while Production Part Approval Process (PPAP) confirms that the production process can consistently meet customer requirements. This course explains why APQP and PPAP are required, how they are connected, and how they support successful product launches and customer satisfaction.",
      "The training focuses on practical application, commonly required in IATF 16949 and automotive customer requirements.",
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Clear understanding of APQP and PPAP requirements",
      "Ability to support new product development and launch activities",
      "Knowledge to prepare and review APQP and PPAP documents",
      "Improved coordination between design, production, and quality teams",
      "Better readiness for customer audits and approvals",
      "Strong support for IATF 16949 compliance and continual improvement",
    ],

    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Introduction to APQP and PPAP concepts and objectives",
      "Relationship between APQP, PPAP, FMEA, Control Plan, SPC, and MSA",
      "APQP phases and key deliverables",
      "Understanding customer requirements and risk-based planning",
      "PPAP requirements, submission levels, and timing",
      "Overview of PPAP elements and documentation",
      "Preparation of Part Submission Warrant (PSW)",
      "Common issues during APQP and PPAP implementation",
      "Practical examples and case discussions",
    ],

    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Lean Management",
    value: "Kanban System Implementation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Lean Management",
    value: "Value Stream Mapping (VSM)",
    mainService: "Consulting",
    img: img1,
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Total Productive Maintenance (TPM)",
    value: "Overall Equipment Effectiveness (OEE) Analysis",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Total Productive Maintenance (TPM)",
    value: "Overall Equipment Effectiveness (OEE) Improvement",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Total Productive Maintenance (TPM)",
    value: "TPM Pillar Implementation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Total Productive Maintenance (TPM)",
    value: "TPM Training",
    mainService: "Training",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Total Productive Maintenance (TPM)",
    value: "Autonomous Maintenance Program Implementation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Total Productive Maintenance (TPM)",
    value: "Planned Maintenance Program Implementation",
    mainService: "Consulting",
    img: img1,
  },

  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Fire Risk Assessments as per IS Standards",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Fire Risk Assessments as per NBC",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Design Audits of Fire Detection Systems",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Adequacy Audits of Fire Protection Systems",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Emergency Response Planning",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Evacuation Planning (ERDMP)",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Supply of Fire Systems",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Installation of Fire Systems",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Fire Detection Mapping",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Fire Gas Detection Mapping",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Arc Flash Risk Assessments",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Hazard Analysis",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Electrical Safety Audits",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Infrared Thermography Studies",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Short Circuit Studies",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Relay Coordination Studies",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Harmonics Studies",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Lockout Tagout (LOTO) Procedure Development",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Lockout Tagout (LOTO) Mapping",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "LPS Adequacy Audits",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Comprehensive Construction Safety Management at Site",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Contractor Safety Management",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Contractor Safety Evaluation",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Ladder Inspection",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Scaffolding Inspection",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Scaffolding Certification",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Work at Height Safety Programs",
    mainService: "Training",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Lifting Safety Programs",
    mainService: "Training",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Logistics and Warehouse Safety",
    value: "Warehouse Risk Assessment",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Logistics and Warehouse Safety",
    value: "Warehouse Layout Design",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Logistics and Warehouse Safety",
    value: "Transportation Safety Management",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Logistics and Warehouse Safety",
    value: "Fleet Audits",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Logistics and Warehouse Safety",
    value: "Journey Risk Management",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Behavior-Based Safety (BBS)",
    value: "Safety Culture Assessment",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Behavior-Based Safety (BBS)",
    value: "Safety Culture Transformation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Behavior-Based Safety (BBS)",
    value: "BBS Program Design",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Behavior-Based Safety (BBS)",
    value: "BBS Program Implementation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Behavior-Based Safety (BBS)",
    value: "Safety Observation Training",
    mainService: "Training",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Behavior-Based Safety (BBS)",
    value: "Safety Feedback Training",
    mainService: "Training",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "LMS Implementation",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "LMS Customization",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Custom E-learning Module Development",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Online Training Delivery",
    mainService: "Training",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Training Tracking",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Training Certification",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Blended Learning Solutions",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Classroom Learning Integration",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Digital Learning Integration",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "LPS Adequacy Audits",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Real-time EHS KPI Dashboards",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Real-time Quality KPI Dashboards",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Data Integration from Multiple Sources",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Unified Data View",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Predictive Analytics",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Proactive Risk Management",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Executive Reporting",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Business Intelligence",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Ready-to-use ISO Document Toolkits",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Certification Acceleration Toolkits",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Professional Training Presentations",
    mainService: "Training",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Professional E-books",
    mainService: "Training",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Customizable Checklists",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Implementation Guides",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Digital Newsletters",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Knowledge Resources",
    mainService: "Training",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Management Systems Training",
    value: "ISO 9001 QMS Awareness",
    mainService: "Training",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Leadership & Soft Skills",
    value: "Strategic Decision-Making for Leaders",
    mainService: "Training",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Technical Training",
    value: "Fire Safety Training",
    mainService: "Training",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Quality Tools Training",
    value: "Six Sigma Green Belt",
    mainService: "Training",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Identification of Skills for Critical EHSQ Roles",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Development of Competency Matrix",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Training Plan Development",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Competency Assessment Programs",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Competency Verification Programs",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Skill Gap Analysis",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Skill Development Plans",
    mainService: "Consulting",
    img: img1,
  },
];

export default servicesCardData;
