import img1 from "../assets/images/nature.jpg";

const servicesCardData = [
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Six Sigma",
    value: "ISO 9001:2015 REFRESHER COURSEISO",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "WHY ", highlight: false },
      { text: "ISO 9001:2015", highlight: true },
      { text: " REFRESHER COURSE?", highlight: false },
    ],
    paragrapgh:[
      "The ISO 9001:2015 Refresher Course is designed forprofessionals who already have a working knowledge of Quality Management Systems and want to realign withcurrent ISO 9001 requirements. The training revisits coreconcepts, clarifies key clauses, and highlights practicalimplications of the standard to ensure effectiveimplementation and sustained compliance. It helpsparticipants sharpen their understanding and confidentlysupport QMS maintenance and continual improvement."],
    subHeading: "What You'll Gain :",
    listItems: [
      "Review updates and critical interpretations of ISO 9001:2015",
      "Apply ISO 9001 requirements to real-world operational scenarios",
      "Gain practical insights into continual improvement and performance evaluation ",
      "Discuss case studies showcasing effective and successful QMS implementation",
    ],
    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Overview and intent of ISO 9001:2015 clauses ",
      "Key updates, interpretations, and common gaps in implementation",
      "Quality Management Principles and their practical application ",
      "Process approach, risk-based thinking, and PDCA cycle ",
      "Documentation and record control: what to retain, what to simplify ",
      "Roles, responsibilities, and leadership involvement in QMS",
      "Case Discussions and Interactive Q&A ",
    ],
    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Six Sigma",
    value: "ISO 9001:2015 AWARENESS SESSION",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "WHY ", highlight: false },
      { text: "ISO 9001:2015", highlight: true },
      { text: " AWARENESS SESSION?", highlight: false },
    ],
    paragrapgh:[
      "The ISO 9001:2015 Awareness Session is designed to build a common understanding of QMS requirements across all levels of the organization. It helps employees recognize how ISO 9001 applies to their daily roles, why compliance matters, and how individual actions contribute to quality objectives and customer satisfaction. This session supports smooth QMS implementation and strengthens engagement during audits and continual improvement initiatives."],
    subHeading: "What You'll Gain :",
    listItems: [
      "Clear understanding of ISO 9001:2015 intent and key requirements",
      "Awareness of employee roles and responsibilities within the QMS",
      "Improved alignment between day-to-day activities and quality objectives",
      "Better preparedness for internal and external audits",
      "Enhanced ownership and participation in quality improvement ",
    ],
    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Purpose and benefits of ISO 9001:2015 ",
      "Overview of the standard and High-Level Structure (Annex SL) ",
      "Quality policy, objectives, and their relevance to employees ",
      "Process approach and riskbased thinking in daily work",
      "Roles of employees in maintaining QMS effectiveness",
      "Audit awareness and do’s & don’ts during assessments",
      "Case Discussions and Interactive Q&A ",
    ],
    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Six Sigma",
    value: "FIRE SAFETY TRAINING",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "WHY ", highlight: false },
      { text: "FIRE SAFETY?", highlight: true },
    ],
    paragrapgh:[
      "Fire incidents escalate rapidly and cause severe loss to life, assets, and business continuity, most fires result from preventable unsafe conditions and delayed response. Fire Safety Training focuses on building awareness, preparedness, and correct response behaviors so employees can prevent fires, react quickly, and minimize impact. Ratherthan only relying on equipment and procedures, this training empowers people to recognize fire risks, use firefighting systems correctly, and respond calmly during emergencies."],
    subHeading: "What You'll Gain :",
    listItems: [
      "Reduced fire risk through early hazard identification and prevention ",
      "Faster, safer response during fire and evacuation scenarios ",
      "Improved confidence in using fire extinguishers and emergency systems ",
      "Compliance with statutory and insurance requirements ",
      "A prepared workforce aligned with emergency response roles and responsibilities ",
    ],
    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Introduction to Fire Behavior and the Fire Triangle ",
      "Types and Classes of Fire",
      "Common Workplace Fire Hazards and Prevention Tips ",
      "Introduction to Fire Extinguishers and Their Applications ",
      "Emergency Evacuation Procedures and Safe Assembly ",
      "Roles of Employees During a Fire Emergency ",
      "Basic Fire Safety Do’s & Don’ts ",
      "Case Discussions and Interactive Q&A ",
    ],
    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Six Sigma",
    value: "BEHAVIOR BASED SAFETY (BBS) TRAINING",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "WHY ", highlight: false },
      { text: "BBS SAFETY?", highlight: true },
    ],
    paragrapgh:[
      "It is found that 90% of workplace accidents are triggered by ‘unsafe acts’. Behavioural safety provides a way of reducing injuries, through the analysis of the risk behaviors in the current work environment. BBS's purpose is not to enforce safety rules, force change, etc. Its purpose is to identify safe and at-risk behaviours, identify the possibility for injury, communicating the risk & helping to identify safer solutions.",
      "Despite having introduced numerous safety systems, which have reduced hazards & improved safety performance,accidents could not get eliminated. Rather stressing on implementation of procedures / rules & regulations, wemotivate people for behaving safely"
  ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Reduced incidents and injuries through proactive behavior change ",
      "Improved employee engagement in safety programs ",
      "A sustainable, observation-driven safety culture ",
      "Tools for real-time feedback and continuous improvement",
      "Aligned leadership and workforce on safety expectations ",
    ],
    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Introduction to Fire Behavior and the Fire Triangle ",
      "Types and Classes of Fire",
      "Common Workplace Fire Hazards and Prevention Tips ",
      "Introduction to Fire Extinguishers and Their Applications ",
      "Emergency Evacuation Procedures and Safe Assembly ",
      "Roles of Employees During a Fire Emergency ",
      "Basic Fire Safety Do’s & Don’ts ",
      "Case Discussions and Interactive Q&A ",
    ],
    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },
  
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Six Sigma",
    value: "ISO 9001:2015 INTRODUCTION TO QMS",
    mainService: "Consulting",
    img: img1,
    headingParts: [
      { text: "WHY INTRODUCTION TO", highlight: false },
      { text: " QMS? ", highlight: true },
    ],
    paragrapgh:[
      "The ISO 9001:2015 Introduction to QMS training provides a clear and practical overview of Quality Management System fundamentals for professionals and organizations beginning their ISO journey. The course explains the intent, structure, and key requirements of ISO 9001, helping participants understand how a process-based approach improves quality, efficiency, and customer satisfaction. It sets a strong foundation for effective implementation and future certification."
  ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Understand the basic principles and structure of ISO 9001:2015",
      "Identify key ISO 9001 requirements and their role in continual improvement ",
      "Learn essential documentation and record-keeping practices for compliance ",
      " Gain clarity on the steps to initiate ISO 9001 certification for an organization",
    ],
    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Overview of Quality Management Systems and ISO philosophy ",
      "ISO 9001:2015 structure (High-Level Structure – Annex SL) ",
      "Quality management principles and process approach ",
      "Documented information: policies, procedures, and records ",
      "Basic roadmap for ISO 9001 implementation and certification",
      "Case Discussions and Interactive Q&A ",
    ],
    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },






  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "5-S Implementation",
    mainService: "Consulting",
    img: img1,
     headingParts: [
      { text: "ISO 9001:2015 Internal Auditors Training Course", highlight: false },
      { text: "", highlight: true },
    ],
    paragrapgh:[
      "The ISO 9001:2015 Internal Auditors Training Course is designed to develop competent internal auditors who can effectively evaluate, maintain, and improve an organization’s Quality Management System (QMS)."
    ],
    subHeading: "What You'll Gain :",
    listItems: [
      "Understand the basic principles and  structure of ISO 9001:2015",
      "Identify key ISO 9001 requirements and their role in continual improvement ",
      "Learn essential documentation and record-keeping practices for compliance ",
      "Gain clarity on the steps to initiate ISO 9001 certification for an organization",
    ],
    secondSubHeading: "What We Cover During Trainings :",
    secondListItems: [
      "Overview of Quality Management Systems and ISO philosophy ",
      "ISO 9001:2015 structure (High-Level Structure – Annex SL) ",
      "Quality management principles and process approach ",
      "Documented information: policies, procedures, and records ",
      "Basic roadmap for ISO 9001 implementation and certification",
      "Case Discussions and Interactive Q&A ",
    ],
    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText:
      "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg:
      "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    downloadPdf:
      "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "5-S Trainings",
    mainService: "Training",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "5-S Workshops",
    mainService: "Training",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "5-S Audits",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "Visual Management System Design",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "Visual Management System Development",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "Standard Operating Procedures Creation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "Work Instruction Creation",
    mainService: "Consulting",
    img: img1,
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Supplier Quality Management",
    value: "Supplier Assessment",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Supplier Quality Management",
    value: "Supplier Development Programs",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Supplier Quality Management",
    value: "Supplier Audits",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Supplier Quality Management",
    value: "Supplier Performance Monitoring",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Supplier Quality Management",
    value: "Collaborative Quality Improvement Initiatives",
    mainService: "Consulting",
    img: img1,
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Lean Management",
    value: "Kaizen Event Facilitation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Lean Management",
    value: "Waste Reduction – Muda",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Lean Management",
    value: "Waste Reduction – Muri",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Lean Management",
    value: "Waste Reduction – Mura",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Lean Management",
    value: "Just-In-Time (JIT) Implementation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Lean Management",
    value: "Kanban System Implementation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Lean Management",
    value: "Value Stream Mapping (VSM)",
    mainService: "Consulting",
    img: img1,
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Total Productive Maintenance (TPM)",
    value: "Overall Equipment Effectiveness (OEE) Analysis",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Total Productive Maintenance (TPM)",
    value: "Overall Equipment Effectiveness (OEE) Improvement",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Total Productive Maintenance (TPM)",
    value: "TPM Pillar Implementation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Total Productive Maintenance (TPM)",
    value: "TPM Training",
    mainService: "Training",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Total Productive Maintenance (TPM)",
    value: "Autonomous Maintenance Program Implementation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Total Productive Maintenance (TPM)",
    value: "Planned Maintenance Program Implementation",
    mainService: "Consulting",
    img: img1,
  },

  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Fire Risk Assessments as per IS Standards",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Fire Risk Assessments as per NBC",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Design Audits of Fire Detection Systems",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Adequacy Audits of Fire Protection Systems",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Emergency Response Planning",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Evacuation Planning (ERDMP)",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Supply of Fire Systems",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Installation of Fire Systems",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Fire Detection Mapping",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Fire Gas Detection Mapping",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Arc Flash Risk Assessments",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Hazard Analysis",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Electrical Safety Audits",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Infrared Thermography Studies",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Short Circuit Studies",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Relay Coordination Studies",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Harmonics Studies",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Lockout Tagout (LOTO) Procedure Development",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Lockout Tagout (LOTO) Mapping",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "LPS Adequacy Audits",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Comprehensive Construction Safety Management at Site",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Contractor Safety Management",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Contractor Safety Evaluation",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Ladder Inspection",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Scaffolding Inspection",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Scaffolding Certification",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Work at Height Safety Programs",
    mainService: "Training",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Lifting Safety Programs",
    mainService: "Training",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Logistics and Warehouse Safety",
    value: "Warehouse Risk Assessment",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Logistics and Warehouse Safety",
    value: "Warehouse Layout Design",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Logistics and Warehouse Safety",
    value: "Transportation Safety Management",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Logistics and Warehouse Safety",
    value: "Fleet Audits",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Logistics and Warehouse Safety",
    value: "Journey Risk Management",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Behavior-Based Safety (BBS)",
    value: "Safety Culture Assessment",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Behavior-Based Safety (BBS)",
    value: "Safety Culture Transformation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Behavior-Based Safety (BBS)",
    value: "BBS Program Design",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Behavior-Based Safety (BBS)",
    value: "BBS Program Implementation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Behavior-Based Safety (BBS)",
    value: "Safety Observation Training",
    mainService: "Training",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Behavior-Based Safety (BBS)",
    value: "Safety Feedback Training",
    mainService: "Training",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "LMS Implementation",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "LMS Customization",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Custom E-learning Module Development",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Online Training Delivery",
    mainService: "Training",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Training Tracking",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Training Certification",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Blended Learning Solutions",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Classroom Learning Integration",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Digital Learning Integration",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "LPS Adequacy Audits",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Real-time EHS KPI Dashboards",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Real-time Quality KPI Dashboards",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Data Integration from Multiple Sources",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Unified Data View",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Predictive Analytics",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Proactive Risk Management",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Executive Reporting",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Business Intelligence",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Ready-to-use ISO Document Toolkits",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Certification Acceleration Toolkits",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Professional Training Presentations",
    mainService: "Training",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Professional E-books",
    mainService: "Training",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Customizable Checklists",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Implementation Guides",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Digital Newsletters",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Knowledge Resources",
    mainService: "Training",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Management Systems Training",
    value: "ISO 9001 QMS Awareness",
    mainService: "Training",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Leadership & Soft Skills",
    value: "Strategic Decision-Making for Leaders",
    mainService: "Training",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Technical Training",
    value: "Fire Safety Training",
    mainService: "Training",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Quality Tools Training",
    value: "Six Sigma Green Belt",
    mainService: "Training",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Identification of Skills for Critical EHSQ Roles",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Development of Competency Matrix",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Training Plan Development",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Competency Assessment Programs",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Competency Verification Programs",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Skill Gap Analysis",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Skill Development Plans",
    mainService: "Consulting",
    img: img1,
  },
];

export default servicesCardData;
