import img1 from "../assets/images/nature.jpg";
import qualityCardImg from "../assets/images/service_image/brochure_eGrowth.jpg";

const servicesCardData = [
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Six Sigma",
    value: "DMAIC Project Implementation",
    mainService: "Consulting",
    img: img1,
    Heading: "Why Fire Safety?",
    paragrapgh:"Fire emergencies can occur anytime, anywhere often due to small, overlooked hazards. Most fires are preventable when people understand how fires start, how to stop them from spreading, and what actions to take in the first few critical minutes. Our Fire Safety Training helps participants recognize risks, understand fire prevention principles, and respond effectively in emergencies.",
    subHeading: "What We Cover During Trainings:",
    listItems: [
     "Introduction to Fire Behavior and the Fire Triangle",
     "Types and Classes of Fire",
     "Common Workplace Fire Hazards and Prevention Tips",
     "Introduction to Fire Extinguishers and Their Applications",
     "Emergency Evacuation Procedures and Safe Assembly",
     "Roles of Employees During a Fire Emergency",
     "Basic Fire Safety Do's & Don'ts",
     "Case Discussions and Interactive Q&A"
    ],
    downlaodheadingText: "ISO 45001 Gap Analysis Checklist (Excel)",
    downlaodheadingSubText: "Comprehensive assessment tool covering all ISO 45001 requirements with scoring methodology and implementation priority guidance.",
    downlaodheadingImg: qualityCardImg,
    downloadPdf: "../../public/service_pdf/Fire Safety Assessment Report_UIL_03.05.2025.pdf",
    media: [
      {
        id: 1,
        type: "image",
        url: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Modern Architecture",
      },
      {
        id: 2,
        type: "video",
        url: "https://www.youtube.com/embed/MFLVmAE4cqg?si=p1FgakYdmIl50WZm",
        title: "Interior Space",
      },
      {
        id: 3,
        type: "image",
        url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Contemporary Living",
      },
      {
        id: 4,
        type: "image",
        url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Urban Design",
      },
    ],
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Six Sigma",
    value: "DMADV Project Implementation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Six Sigma",
    value: "Green Belt Project Mentoring",
    mainService: "Training",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Six Sigma",
    value: "Black Belt Project Mentoring",
    mainService: "Training",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Six Sigma",
    value: "Statistical Process Control (SPC)",
    mainService: "Software Solution",
    img: img1,
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "5-S Implementation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "5-S Trainings",
    mainService: "Training",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "5-S Workshops",
    mainService: "Training",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "5-S Audits",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "Visual Management System Design",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "Visual Management System Development",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "Standard Operating Procedures Creation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "5-S Workplace Organization",
    value: "Work Instruction Creation",
    mainService: "Consulting",
    img: img1,
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Supplier Quality Management",
    value: "Supplier Assessment",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Supplier Quality Management",
    value: "Supplier Development Programs",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Supplier Quality Management",
    value: "Supplier Audits",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Supplier Quality Management",
    value: "Supplier Performance Monitoring",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Supplier Quality Management",
    value: "Collaborative Quality Improvement Initiatives",
    mainService: "Consulting",
    img: img1,
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Lean Management",
    value: "Kaizen Event Facilitation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Lean Management",
    value: "Waste Reduction – Muda",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Lean Management",
    value: "Waste Reduction – Muri",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Lean Management",
    value: "Waste Reduction – Mura",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Lean Management",
    value: "Just-In-Time (JIT) Implementation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Lean Management",
    value: "Kanban System Implementation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Lean Management",
    value: "Value Stream Mapping (VSM)",
    mainService: "Consulting",
    img: img1,
  },

  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Total Productive Maintenance (TPM)",
    value: "Overall Equipment Effectiveness (OEE) Analysis",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Total Productive Maintenance (TPM)",
    value: "Overall Equipment Effectiveness (OEE) Improvement",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Total Productive Maintenance (TPM)",
    value: "TPM Pillar Implementation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Total Productive Maintenance (TPM)",
    value: "TPM Training",
    mainService: "Training",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Total Productive Maintenance (TPM)",
    value: "Autonomous Maintenance Program Implementation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "QUALITY & BUSINESS EXCELLENCE",
    category: "Total Productive Maintenance (TPM)",
    value: "Planned Maintenance Program Implementation",
    mainService: "Consulting",
    img: img1,
  },

  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Fire Risk Assessments as per IS Standards",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Fire Risk Assessments as per NBC",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Design Audits of Fire Detection Systems",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Adequacy Audits of Fire Protection Systems",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Emergency Response Planning",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Evacuation Planning (ERDMP)",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Supply of Fire Systems",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Installation of Fire Systems",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Fire Detection Mapping",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Fire Safety",
    value: "Fire Gas Detection Mapping",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Arc Flash Risk Assessments",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Hazard Analysis",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Electrical Safety Audits",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Infrared Thermography Studies",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Short Circuit Studies",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Relay Coordination Studies",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Harmonics Studies",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Lockout Tagout (LOTO) Procedure Development",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "Lockout Tagout (LOTO) Mapping",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Electrical Safety",
    value: "LPS Adequacy Audits",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Comprehensive Construction Safety Management at Site",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Contractor Safety Management",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Contractor Safety Evaluation",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Ladder Inspection",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Scaffolding Inspection",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Scaffolding Certification",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Work at Height Safety Programs",
    mainService: "Training",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Construction Safety",
    value: "Lifting Safety Programs",
    mainService: "Training",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Logistics and Warehouse Safety",
    value: "Warehouse Risk Assessment",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Logistics and Warehouse Safety",
    value: "Warehouse Layout Design",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Logistics and Warehouse Safety",
    value: "Transportation Safety Management",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Logistics and Warehouse Safety",
    value: "Fleet Audits",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Logistics and Warehouse Safety",
    value: "Journey Risk Management",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Behavior-Based Safety (BBS)",
    value: "Safety Culture Assessment",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Behavior-Based Safety (BBS)",
    value: "Safety Culture Transformation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Behavior-Based Safety (BBS)",
    value: "BBS Program Design",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Behavior-Based Safety (BBS)",
    value: "BBS Program Implementation",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Behavior-Based Safety (BBS)",
    value: "Safety Observation Training",
    mainService: "Training",
    img: img1,
  },
  {
    title: "ENVIRONMENT, HEALTH & SAFETY SOLUTIONS",
    category: "Behavior-Based Safety (BBS)",
    value: "Safety Feedback Training",
    mainService: "Training",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "LMS Implementation",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "LMS Customization",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Custom E-learning Module Development",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Online Training Delivery",
    mainService: "Training",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Training Tracking",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Training Certification",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Blended Learning Solutions",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Classroom Learning Integration",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "Digital Learning Integration",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital LMS Platforms",
    value: "LPS Adequacy Audits",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Real-time EHS KPI Dashboards",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Real-time Quality KPI Dashboards",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Data Integration from Multiple Sources",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Unified Data View",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Predictive Analytics",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Proactive Risk Management",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Executive Reporting",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Performance Dashboards",
    value: "Business Intelligence",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Ready-to-use ISO Document Toolkits",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Certification Acceleration Toolkits",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Professional Training Presentations",
    mainService: "Training",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Professional E-books",
    mainService: "Training",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Customizable Checklists",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Implementation Guides",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Digital Newsletters",
    mainService: "Software Solution",
    img: img1,
  },
  {
    title: "SOFTWARE & DIGITAL SOLUTIONS",
    category: "Digital Resources & Toolkits",
    value: "Knowledge Resources",
    mainService: "Training",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Management Systems Training",
    value: "ISO 9001 QMS Awareness",
    mainService: "Training",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Leadership & Soft Skills",
    value: "Strategic Decision-Making for Leaders",
    mainService: "Training",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Technical Training",
    value: "Fire Safety Training",
    mainService: "Training",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Quality Tools Training",
    value: "Six Sigma Green Belt",
    mainService: "Training",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Identification of Skills for Critical EHSQ Roles",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Development of Competency Matrix",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Training Plan Development",
    mainService: "Consulting",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Competency Assessment Programs",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Competency Verification Programs",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Skill Gap Analysis",
    mainService: "Auditing",
    img: img1,
  },
  {
    title: "TRAINING & COMPETENCY DEVELOPMENT",
    category: "Competency Management",
    value: "Skill Development Plans",
    mainService: "Consulting",
    img: img1,
  },
];

export default servicesCardData;
